dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.0.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.2
  - smartcontractkit/chainlink-brownie-contracts@1.2.0
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
reports:
  exclude_contracts:
    - LinkToken
    - VRFCoordinatorMock
    - ERC721
    - EnumerableMap
    - Address
    - EnumerableSet
compiler:
  solc:
    version: null
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.0.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.2.0'
      - '@openzeppelinUpgrades=OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.2'
      - '@chainlinkOld=smartcontractkit/chainlink-brownie-contracts@1.1.1'
networks:
  mainnet-fork-dev:
    keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 100000000000000000 # 0.1
  development:
    keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 100000000000000000 # 0.1
  rinkeby:
    vrf_coordinator: '0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B'
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709' 
    keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 100000000000000000 # 0.1

